name=ESP32-Robot-Controller
version=1.0.0
author=Nathan Stark
maintainer=Nathan Stark
sentence=Provides framework to control robots using a custom ESP32 board.
paragraph=Provides motor control, servo control, and bluetooth controller abstraction via Bluepad32.
category=Communication
architectures=esp32